// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatedBy struct {
	ID          *int    `json:"id"`
	CreditID    *string `json:"credit_id"`
	Name        *string `json:"name"`
	Gender      *string `json:"gender"`
	ProfilePath *string `json:"profile_path"`
}

type CreditCastItem struct {
	Adult              *bool    `json:"adult"`
	Gender             *int     `json:"gender"`
	ID                 int      `json:"id"`
	KnownForDepartment *string  `json:"known_for_department"`
	Name               *string  `json:"name"`
	OriginalName       *string  `json:"original_name"`
	Popularity         *float64 `json:"popularity"`
	ProfilePath        *string  `json:"profile_path"`
	CastID             *int     `json:"cast_id"`
	Character          *string  `json:"character"`
	CreditID           *string  `json:"credit_id"`
	Order              *int     `json:"order"`
}

type CreditCrewItem struct {
	Adult              *bool    `json:"adult"`
	Gender             *int     `json:"gender"`
	ID                 int      `json:"id"`
	KnownForDepartment *string  `json:"known_for_department"`
	Name               *string  `json:"name"`
	OriginalName       *string  `json:"original_name"`
	Popularity         *float64 `json:"popularity"`
	ProfilePath        *string  `json:"profile_path"`
	CreditID           *string  `json:"credit_id"`
	Department         *string  `json:"department"`
	Job                *string  `json:"job"`
}

type Episode struct {
	AirDate        *string  `json:"air_date"`
	EpisodeNumber  *int     `json:"episode_number"`
	ID             int      `json:"id"`
	Name           *string  `json:"name"`
	Overview       *string  `json:"overview"`
	ProductionCode *string  `json:"production_code"`
	SeasonNumber   *int     `json:"season_number"`
	StillPath      *string  `json:"still_path"`
	VoteAverage    *float64 `json:"vote_average"`
	VoteCount      *int     `json:"vote_count"`
}

type Genre struct {
	ID   *int    `json:"id"`
	Name *string `json:"name"`
}

type ImageItem struct {
	AspectRatio *float64 `json:"aspect_ratio"`
	FilePath    *string  `json:"file_path"`
	Height      *int     `json:"height"`
	Iso639_1    *string  `json:"iso_639_1"`
	VoteAverage *float64 `json:"vote_average"`
	VoteCount   *int     `json:"vote_count"`
	Width       *int     `json:"width"`
}

type Introduction struct {
	Name    string `json:"Name"`
	Message string `json:"Message"`
}

type KnownForItem struct {
	PosterPath       *string  `json:"poster_path"`
	Adult            *bool    `json:"adult"`
	Overview         *string  `json:"overview"`
	ReleaseDate      *string  `json:"release_date"`
	OriginalTitle    *string  `json:"original_title"`
	GenreIds         []int    `json:"genre_ids"`
	ID               int      `json:"id"`
	MediaType        string   `json:"media_type"`
	OriginalLanguage *string  `json:"original_language"`
	Title            *string  `json:"title"`
	BackdropPath     *string  `json:"backdrop_path"`
	Popularity       *float64 `json:"popularity"`
	VoteCount        *int     `json:"vote_count"`
	Video            *bool    `json:"video"`
	VoteAverage      *float64 `json:"vote_average"`
	FirstAirDate     *string  `json:"first_air_date"`
	OriginCountry    []string `json:"origin_country"`
	Name             *string  `json:"name"`
	OriginalName     *string  `json:"original_name"`
}

type MediaCredit struct {
	Cast []*CreditCastItem `json:"cast"`
	Crew []*CreditCrewItem `json:"crew"`
}

type MediaImages struct {
	Backdrops []*ImageItem `json:"backdrops"`
	Posters   []*ImageItem `json:"posters"`
}

type MediaVideos struct {
	Results []*VideoItem `json:"results"`
}

type Movie struct {
	Detail   *MovieDetail `json:"detail"`
	Popular  *MovieList   `json:"popular"`
	TopRated *MovieList   `json:"top_rated"`
	Upcoming *MovieList   `json:"upcoming"`
}

type MovieDetail struct {
	Adult               *bool                `json:"adult"`
	BackdropPath        *string              `json:"backdrop_path"`
	Budget              *int                 `json:"budget"`
	Genres              []*Genre             `json:"genres"`
	Homepage            *string              `json:"homepage"`
	ID                  int                  `json:"id"`
	ImdbID              *string              `json:"imdb_id"`
	OriginalLanguage    *string              `json:"original_language"`
	OriginalTitle       *string              `json:"original_title"`
	Overview            *string              `json:"overview"`
	Popularity          *float64             `json:"popularity"`
	PosterPath          *string              `json:"poster_path"`
	ProductionCompanies []*ProductionCompany `json:"production_companies"`
	ProductionCountries []*ProductionCountry `json:"production_countries"`
	ReleaseDate         *string              `json:"release_date"`
	Revenue             *int                 `json:"revenue"`
	Runtime             *int                 `json:"runtime"`
	SpokenLanguages     []*SpokenLanguage    `json:"spoken_languages"`
	Status              *string              `json:"status"`
	Tagline             *string              `json:"tagline"`
	Title               *string              `json:"title"`
	Video               *bool                `json:"video"`
	VoteAverage         *float64             `json:"vote_average"`
	VoteCount           *int                 `json:"vote_count"`
	Credits             *MediaCredit         `json:"credits"`
	Videos              *MediaVideos         `json:"videos"`
	Images              *MediaImages         `json:"images"`
	Recommendations     *MovieList           `json:"recommendations"`
	Similar             *MovieList           `json:"similar"`
}

type MovieList struct {
	Page         int              `json:"page"`
	Results      []*MovieListItem `json:"results"`
	TotalResults int              `json:"total_results"`
	TotalPages   int              `json:"total_pages"`
}

type MovieListItem struct {
	PosterPath       *string  `json:"poster_path"`
	Adult            *bool    `json:"adult"`
	Overview         *string  `json:"overview"`
	ReleaseDate      *string  `json:"release_date"`
	GenreIds         []*int   `json:"genre_ids"`
	ID               int      `json:"id"`
	OriginalTitle    *string  `json:"original_title"`
	OriginalLanguage *string  `json:"original_language"`
	Title            *string  `json:"title"`
	BackdropPath     *string  `json:"backdrop_path"`
	Popularity       *float64 `json:"popularity"`
	VoteCount        *int     `json:"vote_count"`
	Video            *bool    `json:"video"`
	VoteAverage      *float64 `json:"vote_average"`
}

type Network struct {
	Name          *string `json:"name"`
	ID            int     `json:"id"`
	LogoPath      *string `json:"logo_path"`
	OriginCountry *string `json:"origin_country"`
}

type People struct {
	Detail  *PersonDetail  `json:"detail"`
	Popular *PopularPeople `json:"popular"`
}

type PersonCreditCast struct {
	ID               int      `json:"id"`
	OriginalLanguage *string  `json:"original_language"`
	EpisodeCount     *int     `json:"episode_count"`
	Overview         *string  `json:"overview"`
	OriginCountry    []string `json:"origin_country"`
	OriginalName     *string  `json:"original_name"`
	GenreIds         []int    `json:"genre_ids"`
	Name             *string  `json:"name"`
	MediaType        *string  `json:"media_type"`
	PosterPath       *string  `json:"poster_path"`
	FirstAirDate     *string  `json:"first_air_date"`
	VoteAverage      *float64 `json:"vote_average"`
	VoteCount        *int     `json:"vote_count"`
	Character        *string  `json:"character"`
	BackdropPath     *string  `json:"backdrop_path"`
	Popularity       *float64 `json:"popularity"`
	CreditID         *string  `json:"credit_id"`
	OriginalTitle    *string  `json:"original_title"`
	Video            *bool    `json:"video"`
	ReleaseDate      *string  `json:"release_date"`
	Title            *string  `json:"title"`
	Adult            *bool    `json:"adult"`
}

type PersonCreditCrew struct {
	ID               int      `json:"id"`
	Department       *string  `json:"department"`
	OriginalLanguage *string  `json:"original_language"`
	EpisodeCount     *int     `json:"episode_count"`
	Job              *string  `json:"job"`
	Overview         *string  `json:"overview"`
	OriginCountry    []string `json:"origin_country"`
	OriginalName     *string  `json:"original_name"`
	VoteCount        *int     `json:"vote_count"`
	Name             *string  `json:"name"`
	MediaType        *string  `json:"media_type"`
	Popularity       *float64 `json:"popularity"`
	CreditID         *string  `json:"credit_id"`
	BackdropPath     *string  `json:"backdrop_path"`
	FirstAirDate     *string  `json:"first_air_date"`
	VoteAverage      *float64 `json:"vote_average"`
	GenreIds         []int    `json:"genre_ids"`
	PosterPath       *string  `json:"poster_path"`
	OriginalTitle    *string  `json:"original_title"`
	Video            *bool    `json:"video"`
	Title            *string  `json:"title"`
	Adult            *bool    `json:"adult"`
	ReleaseDate      *string  `json:"release_date"`
}

type PersonCredits struct {
	Cast []*PersonCreditCast `json:"cast"`
	Crew []*PersonCreditCrew `json:"crew"`
}

type PersonDetail struct {
	Birthday           *string            `json:"birthday"`
	KnownForDepartment *string            `json:"known_for_department"`
	Deathday           *string            `json:"deathday"`
	ID                 int                `json:"id"`
	Name               *string            `json:"name"`
	AlsoKnownAs        []string           `json:"also_known_as"`
	Gender             *int               `json:"gender"`
	Biography          *string            `json:"biography"`
	Popularity         *float64           `json:"popularity"`
	PlaceOfBirth       *string            `json:"place_of_birth"`
	ProfilePath        *string            `json:"profile_path"`
	Adult              *bool              `json:"adult"`
	ImdbID             *string            `json:"imdb_id"`
	Homepage           *string            `json:"homepage"`
	ExternalIds        *PersonExternalIds `json:"external_ids"`
	Images             *PersonImages      `json:"images"`
	CombinedCredits    *PersonCredits     `json:"combined_credits"`
}

type PersonExternalIds struct {
	ImdbID      *string `json:"imdb_id"`
	FacebookID  *string `json:"facebook_id"`
	FreebaseMid *string `json:"freebase_mid"`
	FreebaseID  *string `json:"freebase_id"`
	TvrageID    *string `json:"tvrage_id"`
	TwitterID   *string `json:"twitter_id"`
	InstagramID *string `json:"instagram_id"`
}

type PersonImages struct {
	Profiles []*ImageItem `json:"profiles"`
}

type PopularPeople struct {
	Page         int              `json:"page"`
	Results      []*PopularPerson `json:"results"`
	TotalResults int              `json:"total_results"`
	TotalPages   int              `json:"total_pages"`
}

type PopularPerson struct {
	ProfilePath *string         `json:"profile_path"`
	Adult       *bool           `json:"adult"`
	ID          int             `json:"id"`
	KnownFor    []*KnownForItem `json:"known_for"`
	Name        *string         `json:"name"`
	Popularity  *float64        `json:"popularity"`
}

type ProductionCompany struct {
	Name          *string `json:"name"`
	ID            int     `json:"id"`
	LogoPath      *string `json:"logo_path"`
	OriginCountry *string `json:"origin_country"`
}

type ProductionCountry struct {
	Iso3166_1 *string `json:"iso_3166_1"`
	Name      *string `json:"name"`
}

type Season struct {
	AirDate      *string `json:"air_date"`
	EpisodeCount *int    `json:"episode_count"`
	ID           int     `json:"id"`
	Name         *string `json:"name"`
	Overview     *string `json:"overview"`
	PosterPath   *string `json:"poster_path"`
	SeasonNumber *int    `json:"season_number"`
}

type SpokenLanguage struct {
	Iso639_1    *string `json:"iso_639_1"`
	Name        *string `json:"name"`
	EnglishName *string `json:"english_name"`
}

type Tv struct {
	Detail   *TVDetail `json:"detail"`
	Popular  *TVList   `json:"popular"`
	TopRated *TVList   `json:"top_rated"`
	OnTheAir *TVList   `json:"on_the_air"`
}

type TVDetail struct {
	BackdropPath        *string              `json:"backdrop_path"`
	CreatedBy           []*CreatedBy         `json:"created_by"`
	EpisodeRuntime      []int                `json:"episode_runtime"`
	FirstAirDate        *string              `json:"first_air_date"`
	Genres              []*Genre             `json:"genres"`
	Homepage            *string              `json:"homepage"`
	ID                  int                  `json:"id"`
	InProduction        *bool                `json:"in_production"`
	Languages           []string             `json:"languages"`
	LastAirDate         *string              `json:"last_air_date"`
	LastEpisodeToAir    *Episode             `json:"last_episode_to_air"`
	Name                *string              `json:"name"`
	Networks            []*Network           `json:"networks"`
	NumberOfEpisodes    *int                 `json:"number_of_episodes"`
	NumberOfSeasons     *int                 `json:"number_of_seasons"`
	OriginCountry       []string             `json:"origin_country"`
	OriginalLanguage    *string              `json:"original_language"`
	OriginalName        *string              `json:"original_name"`
	Overview            *string              `json:"overview"`
	Popularity          *float64             `json:"popularity"`
	PosterPath          *string              `json:"poster_path"`
	ProductionCompanies []*ProductionCompany `json:"production_companies"`
	ProductionCountries []*ProductionCountry `json:"production_countries"`
	Seasons             []*Season            `json:"seasons"`
	SpokenLanguages     []*SpokenLanguage    `json:"spoken_languages"`
	Status              *string              `json:"status"`
	Tagline             *string              `json:"tagline"`
	Type                *string              `json:"type"`
	VoteAverage         *float64             `json:"vote_average"`
	VoteCount           *int                 `json:"vote_count"`
}

type TVList struct {
	Page         int           `json:"page"`
	Results      []*TVListItem `json:"results"`
	TotalResults int           `json:"total_results"`
	TotalPages   int           `json:"total_pages"`
}

type TVListItem struct {
	PosterPath       *string  `json:"poster_path"`
	Popularity       *float64 `json:"popularity"`
	ID               int      `json:"id"`
	BackdropPath     *string  `json:"backdrop_path"`
	VoteAverage      *float64 `json:"vote_average"`
	Overview         *string  `json:"overview"`
	FirstAirDate     *string  `json:"first_air_date"`
	OriginCountry    []string `json:"origin_country"`
	GenreIds         []int    `json:"genre_ids"`
	OriginalLanguage *string  `json:"original_language"`
	VoteCount        *int     `json:"vote_count"`
	Name             *string  `json:"name"`
	OriginalName     *string  `json:"original_name"`
}

type Trending struct {
	Page         int             `json:"page"`
	Results      []*TrendingItem `json:"results"`
	TotalPages   int             `json:"total_pages"`
	TotalResults int             `json:"total_results"`
}

type TrendingItem struct {
	PosterPath       *string  `json:"poster_path"`
	Adult            *bool    `json:"adult"`
	Overview         *string  `json:"overview"`
	ReleaseDate      *string  `json:"release_date"`
	GenreIds         []int    `json:"genre_ids"`
	ID               int      `json:"id"`
	OriginalTitle    *string  `json:"original_title"`
	OriginalLanguage *string  `json:"original_language"`
	Title            *string  `json:"title"`
	BackdropPath     *string  `json:"backdrop_path"`
	Popularity       *float64 `json:"popularity"`
	VoteCount        *int     `json:"vote_count"`
	Video            *bool    `json:"video"`
	VoteAverage      *float64 `json:"vote_average"`
	FirstAirDate     *string  `json:"first_air_date"`
	OriginCountry    []string `json:"origin_country"`
	Name             *string  `json:"name"`
	OriginalName     *string  `json:"original_name"`
}

type VideoItem struct {
	Iso639_1    *string `json:"iso_639_1"`
	Iso3166_1   *string `json:"iso_3166_1"`
	Name        *string `json:"name"`
	Key         *string `json:"key"`
	Site        *string `json:"site"`
	Size        *int    `json:"size"`
	Type        *string `json:"type"`
	Official    *bool   `json:"official"`
	PublishedAt *string `json:"published_at"`
	ID          *string `json:"id"`
}
