// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Introduction struct {
	Name    string `json:"Name"`
	Message string `json:"Message"`
}

type Movie struct {
	Popular  *MovieList `json:"popular"`
	TopRated *MovieList `json:"top_rated"`
	Upcoming *MovieList `json:"upcoming"`
}

type MovieList struct {
	Page         int              `json:"page"`
	Results      []*MovieListItem `json:"results"`
	TotalResults int              `json:"total_results"`
	TotalPages   int              `json:"total_pages"`
}

type MovieListItem struct {
	PosterPath       *string  `json:"poster_path"`
	Adult            *bool    `json:"adult"`
	Overview         *string  `json:"overview"`
	ReleaseDate      *string  `json:"release_date"`
	GenreIds         []*int   `json:"genre_ids"`
	ID               int      `json:"id"`
	OriginalTitle    *string  `json:"original_title"`
	OriginalLanguage *string  `json:"original_language"`
	Title            *string  `json:"title"`
	BackdropPath     *string  `json:"backdrop_path"`
	Popularity       *float64 `json:"popularity"`
	VoteCount        *int     `json:"vote_count"`
	Video            *bool    `json:"video"`
	VoteAverage      *float64 `json:"vote_average"`
}

type Tv struct {
	Popular  *TVList `json:"popular"`
	TopRated *TVList `json:"top_rated"`
	OnTheAir *TVList `json:"on_the_air"`
}

type TVList struct {
	Page         int           `json:"page"`
	Results      []*TVListItem `json:"results"`
	TotalResults int           `json:"total_results"`
	TotalPages   int           `json:"total_pages"`
}

type TVListItem struct {
	PosterPath       *string  `json:"poster_path"`
	Popularity       *float64 `json:"popularity"`
	ID               int      `json:"id"`
	BackdropPath     *string  `json:"backdrop_path"`
	VoteAverage      *float64 `json:"vote_average"`
	Overview         *string  `json:"overview"`
	FirstAirDate     *string  `json:"first_air_date"`
	OriginCountry    []string `json:"origin_country"`
	GenreIds         []int    `json:"genre_ids"`
	OriginalLanguage *string  `json:"original_language"`
	VoteCount        *int     `json:"vote_count"`
	Name             *string  `json:"name"`
	OriginalName     *string  `json:"original_name"`
}
